package history

import "testing"

func TestCleanPrompt(t *testing.T) {
	t.Parallel()
	for _, tt := range []struct{ body, want string }{
		{"  Fix the   parser\n", "Fix the parser"},
		{"<environment_context>\n<cwd>/work</cwd>\n</environment_context>", ""},
		{"<environment_context>x</environment_context>\n\nFix it", "Fix it"},
		{"# AGENTS.md instructions for /work\n\n<INSTRUCTIONS>\nrules\n</INSTRUCTIONS>", ""},
		{"# AGENTS.md instructions for /work\n\n<INSTRUCTIONS>rules</INSTRUCTIONS>\nShip it", "Ship it"},
		{"<command-message>review</command-message>\n<command-name>/review</command-name>\n<command-args>high</command-args>", "/review high"},
		{"Caveat: The messages below were generated by the user while running local commands. DO NOT respond.", ""},
		{"<unclosed>keep this", "<unclosed>keep this"},
		{"use a <b>bold</b> word", "use a <b>bold</b> word"},
	} {
		if got := cleanPrompt(tt.body); got != tt.want {
			t.Errorf("cleanPrompt(%q) = %q, want %q", tt.body, got, tt.want)
		}
	}
}
