package history

import (
	"strings"
)

// Boilerplate harnesses send as user messages ahead of what a person typed.
const (
	agentsInstructionsHeader = "# AGENTS.md instructions"
	localCommandCaveat       = "Caveat: The messages below were generated by the user while running local commands"
)

// cleanPrompt returns what a person typed in a user message, without the
// context blocks harnesses inject: leading XML-style blocks such as
// <environment_context> and AGENTS.md instruction headers. A slash command
// becomes its name and arguments. Boilerplate-only messages return "".
func cleanPrompt(body string) string {
	text := strings.TrimSpace(body)
	if strings.HasPrefix(text, localCommandCaveat) {
		return ""
	}
	if strings.HasPrefix(text, agentsInstructionsHeader) {
		_, text, _ = strings.Cut(text, "\n")
		text = strings.TrimSpace(text)
	}
	var command, arguments string
	for {
		name, content, rest, ok := leadingBlock(text)
		if !ok {
			break
		}
		switch name {
		case "command-name":
			command = strings.TrimSpace(content)
		case "command-args":
			arguments = strings.TrimSpace(content)
		}
		text = strings.TrimSpace(rest)
	}
	if text == "" && command != "" {
		text = strings.TrimSpace(command + " " + arguments)
	}
	return strings.Join(strings.Fields(text), " ")
}

// leadingBlock splits a leading <name ...>content</name> or <name .../> block
// from text. Text that does not start with a complete block is not split.
func leadingBlock(text string) (string, string, string, bool) {
	if !strings.HasPrefix(text, "<") {
		return "", "", "", false
	}
	end := 1
	for end < len(text) && blockNameByte(text[end]) {
		end++
	}
	if end == 1 || end == len(text) {
		return "", "", "", false
	}
	name := text[1:end]
	open := strings.IndexByte(text, '>')
	if open < 0 || !blockNameTerminator(text[end]) {
		return "", "", "", false
	}
	if text[open-1] == '/' {
		return name, "", text[open+1:], true
	}
	closing := "</" + name + ">"
	content, rest, ok := strings.Cut(text[open+1:], closing)
	if !ok {
		return "", "", "", false
	}
	return name, content, rest, true
}

func blockNameTerminator(character byte) bool {
	return character == '>' || character == ' ' || character == '/' || character == '\n'
}

func blockNameByte(character byte) bool {
	return character == '-' || character == '_' || character == ':' || character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z' || character >= '0' && character <= '9'
}
